### ISSUE TITLE
Flaky tests on MacOS

### ISSUE THREAD

**Issue by francisdb** [waylayio/kairosdb-scala#12]
Since the last docker for mac update the docker-based integration tests seem to fail from time to time.

Probably related to these:
https://github.com/whisklabs/docker-it-scala/issues/51
https://github.com/whisklabs/docker-it-scala/issues/50

**Comment by viktortnk** [comment]
Looks like https://github.com/whisklabs/docker-it-scala/issues/50 is resolved, and https://github.com/whisklabs/docker-it-scala/issues/51 is using docker-java, which doesn't have support for unix sockets.

**Comment by francisdb** [comment]
@viktortnk I still see timeouts with 0.9.0-M6

sometimes containers don't start (no output) or hang (half boot output, output stream stuck?)
checked only by looking at output logging => https://github.com/waylayio/kairosdb-scala/blob/master/src/it/scala/integration/DockerKairosDBService.scala#L29

Seeing this about 50% of the time when running only a single spec

```
Exception during container initialization
java.util.concurrent.TimeoutException: Futures timed out after [60 seconds]
       	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
       	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
       	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
       	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
       	at scala.concurrent.Await$.result(package.scala:190)
```

also seeing these which I understood should have been fixed?
```
com.spotify.docker.client.LogReader@7dbd9db4 not closed properly
com.spotify.docker.client.LogStream@336d59e2 not closed properly
```

**Comment by francisdb** [comment]
@viktortnk should I create a new issue? That `LogReader@7dbd9db4 not closed properly` could be a hint to the solution?

**Comment by francisdb** [comment]
@viktortnk this seemed to be related to docker for mac beta, with stable all works fine :-)
